### ISSUE TITLE
Unable to determine size of file at

### ISSUE THREAD

**Issue by pkerpedjiev** [GMOD/generic-filehandle#61]
Hey, I'm trying to use the @gmod/vcf loader and am running into this issue:

```
remoteFile.ts:128 Uncaught (in promise) Error: unable to determine size of file at https://pkerp.s3.amazonaws.com/public/HG002_SVs_Tier1_v0.6.vcf.gz
    at RemoteFile._callee4$ (remoteFile.ts:128)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

Here's how I'm calling it:

```
import { TabixIndexedFile } from '@gmod/tabix';
import {RemoteFile} from 'generic-filehandle';

    const tbiIndexed = new TabixIndexedFile({
      filehandle: new RemoteFile(this.dataConfig.url),
      tbiFilehandle: new RemoteFile(`${this.dataConfig.url}.tbi`)
    });

    const headerText = await tbiIndexed.getHeader();
```

Do you notice anything glaringly wrong here? Have you encountered a similar issue before?

Thanks in advance! And thanks for making this modular libraries available. They're really helpful.

**Comment by cmdcolin** [comment]
This is due to the vcf module requesting the size of the file and then that is related to cors having access to Content-Range

http://jbrowse.org/docs/cors.html

Given that this is sometimes not in the default cors configuration of some sites this is sometimes kind of a difficult expectation of the vcf or I think tabix module to have

It might be possible to make tabix not require it but you could try the cors fix

**Comment by pkerpedjiev-zymergen** [comment]
So CORS is enabled and the "Content-Length" header is returned:

![image](https://user-images.githubusercontent.com/44822038/80255243-5ec96d80-8631-11ea-8c0a-41725016dd2f.png)

It's just not placed into the response data structure here:

https://github.com/GMOD/generic-filehandle/blob/master/src/remoteFile.ts#L82

Maybe a non standard `fetch` function is being used?

**Comment by cmdcolin** [comment]
Even if you can the tag is returned in the network tab, it is necessary to allow the JS to access that header and that is the CORS configuration, the CORS configuration needs to allow reading Content-Range or Content-Length (Content-Range is sufficient)

**Comment by pkerpedjiev** [comment]
Sorry, I'm not sure I follow. Where does that permission need to be set?

I was under the impression that CORS determined which information the server sent back. If it's in the response, then it was sent back by the server. Why / where does the JS need to be told to read it?

Again, sorry if I'm being obtuse. I just haven't encountered this issue before.

**Comment by cmdcolin** [comment]
If I saw correctly you have a amazon s3 bucket in your original issue? So I think you can add this CORS stanze to the s3 bucket

http://jbrowse.org/docs/cors.html#amazon-s3

https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html

>Why / where does the JS need to be told to read it?

It is an issue of the JS being allowed to process the results that the server returned, the server returns all those headers regardless but the JS is not allowed to read the results unless the CORS headers are set that Expose the header (hence ExposeHeader). The CORS stuff is pretty annoying, I wish the CORS were just not such a weird issue, but the main thing would be adding that CORS config to your bucket

**Comment by pkerpedjiev** [comment]
That's odd. I have all those set. You can even see it in the  "Access-Control-Expose-Headers" part of the response above.

Anyway, I don't want to take too much of your time. Perhaps I can ask how you typically debug the library? I'm used to running `npm start` and seeing a browser but that  doesn't seem to be set up here. How do you usually get a development environment running?

**Comment by cmdcolin** [comment]
This might be a thing in thise library where it does specifically look for Content-Range instead of Content-Length

See line 81 of remoteFile.js

     const res = response.headers.get('content-range')

Should probably check content-length too, if that does have the right info in it


Generally this library is tested via jest so, clone repo, yarn, yarn test

We simulate the network in our yarn test in test/remoteFile.js


I think that, there is a chance that @gmod/tabix should also be updated to just remove usage of this because it seems like it is not necessary...it is just like a weird guard to try to avoid requests past the end of the file but I don't think that should really be needed

**Comment by cmdcolin** [comment]
By usage of this, I mean trying to determine file size

**Comment by cmdcolin** [comment]
(anyways, main takeaway is that we don't have live network tests in this module. could be interesting but the mocked fetch seems to be ok for most testing purpose)

**Comment by pkerpedjiev** [comment]
OK, thanks for your help! I really appreciate it. I'll poke around some more.

**Comment by pkerpedjiev** [comment]
Ah, enabling the `Content-Range` header in AWS did the trick. Thanks again!

**Comment by cmdcolin** [comment]
Xref here https://github.com/GMOD/tabix-js/pull/99 for tabix simplification
